-- BASELINE SCHEMA SNAPSHOT — generated by `supabase db dump --schema public`
-- from the live project on 2026-08-07.
--
-- Why this file exists: the core domain tables (pantries, pantry_items,
-- shopping_items, areas, pantry_members, profiles) were created through the
-- Supabase dashboard and existed in NO migration, so the repo could not
-- rebuild the database from scratch — a disaster-recovery gap found by the
-- codebase audit.
--
-- This is a SNAPSHOT for recovery and review, not a migration: it is not in
-- supabase/migrations/ and `supabase db push` will not apply it. To rebuild an
-- empty project: run this file first, then the migrations in filename order.
-- Regenerate after schema changes with:
--   supabase db dump --schema public -f supabase/schema/baseline.sql



SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE OR REPLACE FUNCTION "public"."consume_ai_quota"("p_bucket" "text", "p_capacity" integer DEFAULT NULL::integer, "p_window_seconds" integer DEFAULT NULL::integer) RETURNS "jsonb"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
declare
  v_user uuid := auth.uid();
  v_capacity int;
  v_window int;
  v_rate double precision;
  v_row ai_usage%rowtype;
  v_tokens double precision;
begin
  if v_user is null then
    raise exception 'not authenticated';
  end if;

  -- Server-authoritative per-bucket quota. Unknown buckets are denied.
  case p_bucket
    when 'receipts_project' then v_capacity := 5;  v_window := 3600;
    when 'recipes_project'  then v_capacity := 15; v_window := 3600;
    else
      return jsonb_build_object('allowed', false, 'reason', 'unknown_bucket');
  end case;

  v_rate := v_capacity::double precision / v_window;

  insert into ai_usage (user_id, bucket, tokens, last_refill)
  values (v_user, p_bucket, v_capacity, now())
  on conflict (user_id, bucket) do nothing;

  select * into v_row from ai_usage
  where user_id = v_user and bucket = p_bucket
  for update;

  -- Linear refill, capped at capacity (also clamps any inflated value a user
  -- could have written by calling this RPC directly with a huge p_capacity).
  v_tokens := least(
    v_capacity::double precision,
    v_row.tokens + extract(epoch from (now() - v_row.last_refill)) * v_rate
  );

  if v_tokens >= 1 then
    update ai_usage set tokens = v_tokens - 1, last_refill = now()
    where user_id = v_user and bucket = p_bucket;
    return jsonb_build_object('allowed', true, 'remaining', floor(v_tokens - 1));
  end if;

  update ai_usage set tokens = v_tokens, last_refill = now()
  where user_id = v_user and bucket = p_bucket;
  return jsonb_build_object(
    'allowed', false,
    'retry_after_seconds', ceil((1 - v_tokens) / v_rate)
  );
end;
$$;


ALTER FUNCTION "public"."consume_ai_quota"("p_bucket" "text", "p_capacity" integer, "p_window_seconds" integer) OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."consume_pantry_items"("p_pantry_id" "uuid", "p_items" "jsonb") RETURNS TABLE("item_id" "uuid", "item_name" "text", "prev_qty" numeric, "new_qty" numeric, "removed" boolean)
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
declare
  v jsonb;
  v_id uuid;
  v_amount numeric;
  v_prev numeric;
  v_next numeric;
  v_name text;
begin
  if not is_pantry_member(p_pantry_id) then
    raise exception 'not a member of this pantry';
  end if;

  for v in select * from jsonb_array_elements(p_items)
  loop
    v_id := (v->>'id')::uuid;
    v_amount := coalesce((v->>'qty')::numeric, 0);
    if v_amount <= 0 then
      raise exception 'consume amount must be positive for item %', v_id;
    end if;

    -- Lock the row so concurrent cooks can't both read the same starting qty.
    select quantity, name into v_prev, v_name
    from pantry_items
    where id = v_id and pantry_id = p_pantry_id
    for update;

    if v_prev is null then
      raise exception 'item % not found in this pantry', v_id;
    end if;

    v_next := greatest(0, round(v_prev - v_amount, 2));

    if v_next = 0 then
      delete from pantry_items where id = v_id;
      item_id := v_id; item_name := v_name; prev_qty := v_prev; new_qty := 0; removed := true;
    else
      update pantry_items set quantity = v_next where id = v_id;
      item_id := v_id; item_name := v_name; prev_qty := v_prev; new_qty := v_next; removed := false;
    end if;
    return next;
  end loop;
end;
$$;


ALTER FUNCTION "public"."consume_pantry_items"("p_pantry_id" "uuid", "p_items" "jsonb") OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
DECLARE
  v_first_name text;
  v_last_name text;
  v_full_name text;
BEGIN
  v_first_name := NEW.raw_user_meta_data->>'first_name';
  v_last_name := NEW.raw_user_meta_data->>'last_name';
  v_full_name := NEW.raw_user_meta_data->>'full_name';
  
  -- If first_name is missing but full_name exists (e.g., from Google OAuth)
  IF v_first_name IS NULL AND v_full_name IS NOT NULL THEN
    v_first_name := split_part(v_full_name, ' ', 1);
    v_last_name := substring(v_full_name from length(v_first_name) + 2);
  END IF;

  INSERT INTO public.profiles (id, first_name, last_name, avatar_url)
  VALUES (
    NEW.id,
    v_first_name,
    v_last_name,
    NEW.raw_user_meta_data->>'avatar_url'
  );
  RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_updated_at"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."handle_updated_at"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."import_receipt_items"("p_pantry_id" "uuid", "p_items" "jsonb") RETURNS integer
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
declare
  v jsonb;
  v_name text;
  v_count int := 0;
begin
  if not is_pantry_member(p_pantry_id) then
    raise exception 'not a member of this pantry';
  end if;
  if jsonb_typeof(p_items) <> 'array' then
    raise exception 'p_items must be a JSON array';
  end if;

  for v in select * from jsonb_array_elements(p_items) loop
    v_name := trim(coalesce(v->>'name', ''));
    if v_name = '' then
      raise exception 'item name cannot be blank';
    end if;
    insert into pantry_items (pantry_id, area_id, name, category, quantity, unit, expiration_date, notes)
    values (
      p_pantry_id,
      nullif(v->>'area_id', '')::uuid,
      v_name,
      coalesce(nullif(v->>'category', ''), 'other'),
      coalesce((v->>'quantity')::double precision, 1),
      coalesce(nullif(v->>'unit', ''), 'pcs'),
      nullif(v->>'expiration_date', '')::date,
      coalesce(v->>'notes', '')
    );
    v_count := v_count + 1;
  end loop;

  return v_count;
end;
$$;


ALTER FUNCTION "public"."import_receipt_items"("p_pantry_id" "uuid", "p_items" "jsonb") OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."is_pantry_member"("p_pantry_id" "uuid") RETURNS boolean
    LANGUAGE "sql" STABLE SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
  select exists (
    select 1 from pantry_members
    where pantry_id = p_pantry_id and user_id = auth.uid()
  );
$$;


ALTER FUNCTION "public"."is_pantry_member"("p_pantry_id" "uuid") OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."is_pantry_owner"("p_pantry_id" "uuid") RETURNS boolean
    LANGUAGE "sql" STABLE SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
  SELECT EXISTS (
    SELECT 1 FROM pantry_members
    WHERE pantry_id = p_pantry_id
    AND user_id = auth.uid()
    AND role = 'owner'
  );
$$;


ALTER FUNCTION "public"."is_pantry_owner"("p_pantry_id" "uuid") OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."leave_pantry"("p_pantry_id" "uuid") RETURNS "text"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
declare
  v_remaining int;
  v_my_count int;
begin
  if not is_pantry_member(p_pantry_id) then
    raise exception 'not a member of this pantry';
  end if;

  -- Never strand a user with zero households; the app assumes one exists.
  select count(*) into v_my_count from pantry_members where user_id = auth.uid();
  if v_my_count <= 1 then
    raise exception 'you must belong to at least one home';
  end if;

  delete from pantry_members
  where pantry_id = p_pantry_id and user_id = auth.uid();

  select count(*) into v_remaining from pantry_members where pantry_id = p_pantry_id;
  if v_remaining = 0 then
    -- Sole member: take the household and its contents with us.
    delete from shopping_items where pantry_id = p_pantry_id;
    delete from pantry_items where pantry_id = p_pantry_id;
    delete from areas where pantry_id = p_pantry_id;
    delete from pantries where id = p_pantry_id;
    return 'deleted';
  end if;
  return 'left';
end;
$$;


ALTER FUNCTION "public"."leave_pantry"("p_pantry_id" "uuid") OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."move_checked_to_pantry"("p_pantry_id" "uuid", "p_moves" "jsonb") RETURNS "jsonb"
    LANGUAGE "plpgsql"
    SET "search_path" TO 'public'
    AS $$
declare
  v jsonb;
  r shopping_items%rowtype;
  v_moved int := 0;
begin
  if not is_pantry_member(p_pantry_id) then
    raise exception 'not a member of this pantry';
  end if;
  if jsonb_typeof(p_moves) <> 'array' then
    raise exception 'p_moves must be a JSON array';
  end if;

  for v in select * from jsonb_array_elements(p_moves) loop
    select * into r from shopping_items
    where id = (v->>'id')::uuid and pantry_id = p_pantry_id and is_checked
    for update;
    if not found then
      continue;
    end if;

    insert into pantry_items (pantry_id, name, category, quantity, unit, expiration_date, notes)
    values (
      p_pantry_id,
      r.name,
      coalesce(r.category, 'other'),
      coalesce(r.quantity, 1),
      coalesce(r.unit, 'pcs'),
      nullif(v->>'expiration_date', '')::date,
      ''
    );
    delete from shopping_items where id = r.id;
    v_moved := v_moved + 1;
  end loop;

  return jsonb_build_object('moved', v_moved, 'failed', 0);
end;
$$;


ALTER FUNCTION "public"."move_checked_to_pantry"("p_pantry_id" "uuid", "p_moves" "jsonb") OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."redeem_pantry_invite"("p_token" "uuid") RETURNS "jsonb"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
declare
  v_user uuid := auth.uid();
  v_invite invite_tokens%rowtype;
  v_name text;
  v_email text;
begin
  if v_user is null then
    raise exception 'not authenticated';
  end if;

  select * into v_invite from invite_tokens where token = p_token for update;
  if not found then
    return jsonb_build_object('ok', false, 'reason', 'invalid');
  end if;
  if v_invite.expires_at < now() then
    return jsonb_build_object('ok', false, 'reason', 'expired');
  end if;
  if v_invite.use_count >= v_invite.max_uses then
    return jsonb_build_object('ok', false, 'reason', 'exhausted');
  end if;

  select name into v_name from pantries where id = v_invite.pantry_id;

  if exists (
    select 1 from pantry_members
    where pantry_id = v_invite.pantry_id and user_id = v_user
  ) then
    return jsonb_build_object(
      'ok', true, 'already_member', true,
      'pantry_id', v_invite.pantry_id, 'pantry_name', v_name
    );
  end if;

  select email into v_email from auth.users where id = v_user;
  insert into pantry_members (pantry_id, user_id, email, role)
  values (v_invite.pantry_id, v_user, v_email, 'member');
  update invite_tokens set use_count = use_count + 1 where token = p_token;

  return jsonb_build_object(
    'ok', true, 'already_member', false,
    'pantry_id', v_invite.pantry_id, 'pantry_name', v_name
  );
end;
$$;


ALTER FUNCTION "public"."redeem_pantry_invite"("p_token" "uuid") OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."rename_pantry"("p_pantry_id" "uuid", "p_name" "text") RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
begin
  if not is_pantry_member(p_pantry_id) then
    raise exception 'not a member of this pantry';
  end if;
  if coalesce(btrim(p_name), '') = '' then
    raise exception 'name cannot be blank';
  end if;
  update pantries set name = btrim(p_name) where id = p_pantry_id;
end;
$$;


ALTER FUNCTION "public"."rename_pantry"("p_pantry_id" "uuid", "p_name" "text") OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."store_push_subscription"("p_endpoint" "text", "p_p256dh" "text", "p_auth" "text") RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
declare
  v_user uuid := auth.uid();
begin
  if v_user is null then
    raise exception 'not authenticated';
  end if;
  delete from push_subscriptions where endpoint = p_endpoint;
  insert into push_subscriptions (user_id, endpoint, p256dh, auth)
  values (v_user, p_endpoint, p_p256dh, p_auth);
end;
$$;


ALTER FUNCTION "public"."store_push_subscription"("p_endpoint" "text", "p_p256dh" "text", "p_auth" "text") OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."ai_usage" (
    "user_id" "uuid" NOT NULL,
    "bucket" "text" NOT NULL,
    "tokens" double precision NOT NULL,
    "last_refill" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."ai_usage" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."areas" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "pantry_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."areas" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."consumption_events" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "pantry_id" "uuid" NOT NULL,
    "user_id" "uuid" NOT NULL,
    "client_id" "text",
    "item_name" "text" NOT NULL,
    "category" "text",
    "qty" double precision DEFAULT 1 NOT NULL,
    "unit" "text",
    "reason" "text" NOT NULL,
    "meta" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "consumption_events_reason_check" CHECK (("reason" = ANY (ARRAY['used'::"text", 'wasted'::"text", 'donated'::"text", 'other'::"text"])))
);


ALTER TABLE "public"."consumption_events" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."invite_tokens" (
    "token" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "pantry_id" "uuid" NOT NULL,
    "created_by" "uuid" NOT NULL,
    "expires_at" timestamp with time zone DEFAULT ("now"() + '7 days'::interval) NOT NULL,
    "max_uses" integer DEFAULT 10 NOT NULL,
    "use_count" integer DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."invite_tokens" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."pantries" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "created_by" "uuid" NOT NULL
);


ALTER TABLE "public"."pantries" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."pantry_items" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "pantry_id" "uuid" NOT NULL,
    "area_id" "uuid",
    "name" "text" NOT NULL,
    "category" "text" DEFAULT 'other'::"text" NOT NULL,
    "quantity" numeric DEFAULT 1 NOT NULL,
    "unit" "text" DEFAULT 'pcs'::"text" NOT NULL,
    "expiration_date" "date",
    "notes" "text",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."pantry_items" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."pantry_members" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "pantry_id" "uuid" NOT NULL,
    "user_id" "uuid",
    "email" "text",
    "role" "text" DEFAULT 'member'::"text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."pantry_members" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "first_name" "text",
    "last_name" "text",
    "venmo_handle" "text",
    "avatar_url" "text",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."push_subscriptions" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "endpoint" "text" NOT NULL,
    "p256dh" "text" NOT NULL,
    "auth" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."push_subscriptions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."shopping_items" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "pantry_id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "quantity" numeric DEFAULT 1 NOT NULL,
    "unit" "text" DEFAULT 'pcs'::"text" NOT NULL,
    "is_checked" boolean DEFAULT false NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "category" "text" DEFAULT 'other'::"text" NOT NULL
);


ALTER TABLE "public"."shopping_items" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."user_preferences" (
    "user_id" "uuid" NOT NULL,
    "diet" "text" DEFAULT 'all'::"text" NOT NULL,
    "favorite_recipes" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "pinned_items" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "do_not_sell" boolean DEFAULT false NOT NULL
);


ALTER TABLE "public"."user_preferences" OWNER TO "postgres";


ALTER TABLE ONLY "public"."ai_usage"
    ADD CONSTRAINT "ai_usage_pkey" PRIMARY KEY ("user_id", "bucket");



ALTER TABLE ONLY "public"."areas"
    ADD CONSTRAINT "areas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."consumption_events"
    ADD CONSTRAINT "consumption_events_pantry_client_key" UNIQUE ("pantry_id", "client_id");



ALTER TABLE ONLY "public"."consumption_events"
    ADD CONSTRAINT "consumption_events_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."invite_tokens"
    ADD CONSTRAINT "invite_tokens_pkey" PRIMARY KEY ("token");



ALTER TABLE ONLY "public"."pantries"
    ADD CONSTRAINT "pantries_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."pantry_items"
    ADD CONSTRAINT "pantry_items_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."pantry_members"
    ADD CONSTRAINT "pantry_members_pantry_id_email_key" UNIQUE ("pantry_id", "email");



ALTER TABLE ONLY "public"."pantry_members"
    ADD CONSTRAINT "pantry_members_pantry_id_user_id_key" UNIQUE ("pantry_id", "user_id");



ALTER TABLE ONLY "public"."pantry_members"
    ADD CONSTRAINT "pantry_members_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."push_subscriptions"
    ADD CONSTRAINT "push_subscriptions_endpoint_key" UNIQUE ("endpoint");



ALTER TABLE ONLY "public"."push_subscriptions"
    ADD CONSTRAINT "push_subscriptions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."shopping_items"
    ADD CONSTRAINT "shopping_items_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user_preferences"
    ADD CONSTRAINT "user_preferences_pkey" PRIMARY KEY ("user_id");



CREATE INDEX "consumption_events_pantry_created_idx" ON "public"."consumption_events" USING "btree" ("pantry_id", "created_at" DESC);



CREATE OR REPLACE TRIGGER "handle_updated_at" BEFORE UPDATE ON "public"."profiles" FOR EACH ROW EXECUTE FUNCTION "public"."handle_updated_at"();



ALTER TABLE ONLY "public"."ai_usage"
    ADD CONSTRAINT "ai_usage_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."areas"
    ADD CONSTRAINT "areas_pantry_id_fkey" FOREIGN KEY ("pantry_id") REFERENCES "public"."pantries"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."consumption_events"
    ADD CONSTRAINT "consumption_events_pantry_id_fkey" FOREIGN KEY ("pantry_id") REFERENCES "public"."pantries"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."consumption_events"
    ADD CONSTRAINT "consumption_events_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."invite_tokens"
    ADD CONSTRAINT "invite_tokens_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."invite_tokens"
    ADD CONSTRAINT "invite_tokens_pantry_id_fkey" FOREIGN KEY ("pantry_id") REFERENCES "public"."pantries"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."pantries"
    ADD CONSTRAINT "pantries_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."pantry_items"
    ADD CONSTRAINT "pantry_items_area_id_fkey" FOREIGN KEY ("area_id") REFERENCES "public"."areas"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."pantry_items"
    ADD CONSTRAINT "pantry_items_pantry_id_fkey" FOREIGN KEY ("pantry_id") REFERENCES "public"."pantries"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."pantry_members"
    ADD CONSTRAINT "pantry_members_pantry_id_fkey" FOREIGN KEY ("pantry_id") REFERENCES "public"."pantries"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."pantry_members"
    ADD CONSTRAINT "pantry_members_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."push_subscriptions"
    ADD CONSTRAINT "push_subscriptions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."shopping_items"
    ADD CONSTRAINT "shopping_items_pantry_id_fkey" FOREIGN KEY ("pantry_id") REFERENCES "public"."pantries"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."user_preferences"
    ADD CONSTRAINT "user_preferences_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



CREATE POLICY "Manage areas" ON "public"."areas" USING ("public"."is_pantry_member"("pantry_id")) WITH CHECK ("public"."is_pantry_member"("pantry_id"));



CREATE POLICY "Manage pantry items" ON "public"."pantry_items" USING ("public"."is_pantry_member"("pantry_id")) WITH CHECK ("public"."is_pantry_member"("pantry_id"));



CREATE POLICY "Manage shopping items" ON "public"."shopping_items" USING ("public"."is_pantry_member"("pantry_id")) WITH CHECK ("public"."is_pantry_member"("pantry_id"));



CREATE POLICY "Public profiles are viewable by everyone." ON "public"."profiles" FOR SELECT USING (true);



CREATE POLICY "Users can delete members if owner or removing self" ON "public"."pantry_members" FOR DELETE USING ((("auth"."uid"() = "user_id") OR "public"."is_pantry_owner"("pantry_id")));



CREATE POLICY "Users can delete pantries they own" ON "public"."pantries" FOR DELETE USING ("public"."is_pantry_owner"("id"));



CREATE POLICY "Users can insert pantries" ON "public"."pantries" FOR INSERT WITH CHECK (("auth"."uid"() = "created_by"));



CREATE POLICY "Users can insert their own profile." ON "public"."profiles" FOR INSERT WITH CHECK (("auth"."uid"() = "id"));



CREATE POLICY "Users can insert themselves or owner can insert members" ON "public"."pantry_members" FOR INSERT WITH CHECK ((("auth"."uid"() = "user_id") OR (("user_id" IS NULL) AND "public"."is_pantry_owner"("pantry_id"))));



CREATE POLICY "Users can update members if owner or updating self" ON "public"."pantry_members" FOR UPDATE USING ((("auth"."uid"() = "user_id") OR "public"."is_pantry_owner"("pantry_id")));



CREATE POLICY "Users can update own profile." ON "public"."profiles" FOR UPDATE USING (("auth"."uid"() = "id"));



CREATE POLICY "Users can update pantries they are owners of" ON "public"."pantries" FOR UPDATE USING ("public"."is_pantry_owner"("id"));



CREATE POLICY "Users can view members of their pantries" ON "public"."pantry_members" FOR SELECT USING ((("user_id" = "auth"."uid"()) OR "public"."is_pantry_member"("pantry_id")));



CREATE POLICY "Users can view pantries they are members of" ON "public"."pantries" FOR SELECT USING ("public"."is_pantry_member"("id"));



CREATE POLICY "Users can view pantries they created" ON "public"."pantries" FOR SELECT USING (("auth"."uid"() = "created_by"));



ALTER TABLE "public"."ai_usage" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."areas" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."consumption_events" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."invite_tokens" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "members create invites" ON "public"."invite_tokens" FOR INSERT WITH CHECK ((("created_by" = "auth"."uid"()) AND "public"."is_pantry_member"("pantry_id")));



CREATE POLICY "members insert own events" ON "public"."consumption_events" FOR INSERT WITH CHECK ((("user_id" = "auth"."uid"()) AND "public"."is_pantry_member"("pantry_id")));



CREATE POLICY "members read events" ON "public"."consumption_events" FOR SELECT USING ("public"."is_pantry_member"("pantry_id"));



CREATE POLICY "members read invites" ON "public"."invite_tokens" FOR SELECT USING ("public"."is_pantry_member"("pantry_id"));



CREATE POLICY "members revoke invites" ON "public"."invite_tokens" FOR DELETE USING ("public"."is_pantry_member"("pantry_id"));



CREATE POLICY "own prefs insert" ON "public"."user_preferences" FOR INSERT WITH CHECK (("user_id" = "auth"."uid"()));



CREATE POLICY "own prefs select" ON "public"."user_preferences" FOR SELECT USING (("user_id" = "auth"."uid"()));



CREATE POLICY "own prefs update" ON "public"."user_preferences" FOR UPDATE USING (("user_id" = "auth"."uid"())) WITH CHECK (("user_id" = "auth"."uid"()));



CREATE POLICY "own subscriptions" ON "public"."push_subscriptions" USING (("user_id" = "auth"."uid"())) WITH CHECK (("user_id" = "auth"."uid"()));



ALTER TABLE "public"."pantries" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pantry_items" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."pantry_members" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."push_subscriptions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."shopping_items" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."user_preferences" ENABLE ROW LEVEL SECURITY;


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON FUNCTION "public"."consume_ai_quota"("p_bucket" "text", "p_capacity" integer, "p_window_seconds" integer) TO "authenticated";
GRANT ALL ON FUNCTION "public"."consume_ai_quota"("p_bucket" "text", "p_capacity" integer, "p_window_seconds" integer) TO "service_role";



GRANT ALL ON FUNCTION "public"."consume_pantry_items"("p_pantry_id" "uuid", "p_items" "jsonb") TO "anon";
GRANT ALL ON FUNCTION "public"."consume_pantry_items"("p_pantry_id" "uuid", "p_items" "jsonb") TO "authenticated";
GRANT ALL ON FUNCTION "public"."consume_pantry_items"("p_pantry_id" "uuid", "p_items" "jsonb") TO "service_role";



GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";



GRANT ALL ON FUNCTION "public"."handle_updated_at"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_updated_at"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_updated_at"() TO "service_role";



GRANT ALL ON FUNCTION "public"."import_receipt_items"("p_pantry_id" "uuid", "p_items" "jsonb") TO "authenticated";
GRANT ALL ON FUNCTION "public"."import_receipt_items"("p_pantry_id" "uuid", "p_items" "jsonb") TO "service_role";



GRANT ALL ON FUNCTION "public"."is_pantry_member"("p_pantry_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."is_pantry_member"("p_pantry_id" "uuid") TO "service_role";



GRANT ALL ON FUNCTION "public"."is_pantry_owner"("p_pantry_id" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."is_pantry_owner"("p_pantry_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."is_pantry_owner"("p_pantry_id" "uuid") TO "service_role";



GRANT ALL ON FUNCTION "public"."leave_pantry"("p_pantry_id" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."leave_pantry"("p_pantry_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."leave_pantry"("p_pantry_id" "uuid") TO "service_role";



GRANT ALL ON FUNCTION "public"."move_checked_to_pantry"("p_pantry_id" "uuid", "p_moves" "jsonb") TO "authenticated";
GRANT ALL ON FUNCTION "public"."move_checked_to_pantry"("p_pantry_id" "uuid", "p_moves" "jsonb") TO "service_role";



GRANT ALL ON FUNCTION "public"."redeem_pantry_invite"("p_token" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."redeem_pantry_invite"("p_token" "uuid") TO "service_role";



GRANT ALL ON FUNCTION "public"."rename_pantry"("p_pantry_id" "uuid", "p_name" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."rename_pantry"("p_pantry_id" "uuid", "p_name" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."rename_pantry"("p_pantry_id" "uuid", "p_name" "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."store_push_subscription"("p_endpoint" "text", "p_p256dh" "text", "p_auth" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."store_push_subscription"("p_endpoint" "text", "p_p256dh" "text", "p_auth" "text") TO "service_role";



GRANT ALL ON TABLE "public"."ai_usage" TO "anon";
GRANT ALL ON TABLE "public"."ai_usage" TO "authenticated";
GRANT ALL ON TABLE "public"."ai_usage" TO "service_role";



GRANT ALL ON TABLE "public"."areas" TO "anon";
GRANT ALL ON TABLE "public"."areas" TO "authenticated";
GRANT ALL ON TABLE "public"."areas" TO "service_role";



GRANT ALL ON TABLE "public"."consumption_events" TO "anon";
GRANT ALL ON TABLE "public"."consumption_events" TO "authenticated";
GRANT ALL ON TABLE "public"."consumption_events" TO "service_role";



GRANT ALL ON TABLE "public"."invite_tokens" TO "anon";
GRANT ALL ON TABLE "public"."invite_tokens" TO "authenticated";
GRANT ALL ON TABLE "public"."invite_tokens" TO "service_role";



GRANT ALL ON TABLE "public"."pantries" TO "anon";
GRANT ALL ON TABLE "public"."pantries" TO "authenticated";
GRANT ALL ON TABLE "public"."pantries" TO "service_role";



GRANT ALL ON TABLE "public"."pantry_items" TO "anon";
GRANT ALL ON TABLE "public"."pantry_items" TO "authenticated";
GRANT ALL ON TABLE "public"."pantry_items" TO "service_role";



GRANT ALL ON TABLE "public"."pantry_members" TO "anon";
GRANT ALL ON TABLE "public"."pantry_members" TO "authenticated";
GRANT ALL ON TABLE "public"."pantry_members" TO "service_role";



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



GRANT ALL ON TABLE "public"."push_subscriptions" TO "anon";
GRANT ALL ON TABLE "public"."push_subscriptions" TO "authenticated";
GRANT ALL ON TABLE "public"."push_subscriptions" TO "service_role";



GRANT ALL ON TABLE "public"."shopping_items" TO "anon";
GRANT ALL ON TABLE "public"."shopping_items" TO "authenticated";
GRANT ALL ON TABLE "public"."shopping_items" TO "service_role";



GRANT ALL ON TABLE "public"."user_preferences" TO "anon";
GRANT ALL ON TABLE "public"."user_preferences" TO "authenticated";
GRANT ALL ON TABLE "public"."user_preferences" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";







